
import Image from "next/image"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body> <div className="flex flex-col items-center justify-start min-h-screen pt-6 pb-12 px-2 mx-auto text-neutral-50 ">
      <div>
        <Image src="/images/logofull.svg" alt="Conference Logo" width={200} height={50} />
      </div>
      {children}</div>  </body>
    </html>
  )
}
